info:
  app:
    name: Users service - Command Side
    description: Users service - Command Side (CQRS)

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.axonframework: DEBUG
    com.believe: DEBUG

axon:
  amqp:
    exchange: users.events.fanout.exchange
  eventhandling:
    processors:
      name:
        mode: tracking
        source: eventBus

spring:
  application:
    exchange: users.events.fanout.exchange
    queue: users.default.queue
    databaseName: users
    eventsCollectionName: events
    snapshotCollectionName: snapshots
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/users

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

---
spring:
  profiles: docker
  rabbitmq:
    host: my-rabbit
    username: test
    password: password
  data:
    mongodb:
      uri: mongodb://my-mongo:27017/users
